#!/bin/bash
#
# TACACS+ Server Setup Script for AAA Authentication Tests
# Run this script on the TACACS+ server (192.168.100.175)
#
# Usage:
#   sudo bash setup_tacacs_server.sh
#

set -e

echo "=========================================="
echo "TACACS+ Server Setup for SPyTest AAA Tests"
echo "=========================================="
echo ""

# Check if running as root
if [ "$EUID" -ne 0 ]; then
  echo "ERROR: This script must be run as root (use sudo)"
  exit 1
fi

# Variables
TACACS_CONF="/etc/tacacs+/tac_plus.conf"
TACACS_BACKUP="/etc/tacacs+/tac_plus.conf.backup.$(date +%Y%m%d_%H%M%S)"
SERVICE_NAME="tacacs_plus"

echo "[1/6] Checking if tac_plus is installed..."
if ! command -v tac_plus &> /dev/null; then
    echo "  tac_plus not found. Installing..."
    apt update
    apt install -y tacacs+
    echo "  ✓ tac_plus installed"
else
    echo "  ✓ tac_plus is already installed"
fi

echo ""
echo "[2/6] Backing up existing configuration..."
if [ -f "$TACACS_CONF" ]; then
    cp "$TACACS_CONF" "$TACACS_BACKUP"
    echo "  ✓ Backup created: $TACACS_BACKUP"
else
    mkdir -p /etc/tacacs+
    echo "  ✓ Created /etc/tacacs+ directory"
fi

echo ""
echo "[3/6] Creating TACACS+ configuration..."
cat > "$TACACS_CONF" << 'EOF'
# TACACS+ Server Configuration for SPyTest AAA Tests
# Generated by setup_tacacs_server.sh
# Date: $(date)

# Encryption key - MUST match SONiC device configuration
key = spytest_secret123

# Accounting log file
accounting file = /var/log/tac_plus.acct

# Default authentication
default authentication = file /etc/passwd

# ==============================================================================
# TEST USERS FOR AAA AUTHENTICATION TESTS
# ==============================================================================

# User 1: tacacsadmin (Privilege 15 - Full Admin Access)
user = tacacsadmin {
    # Using cleartext password for testing (use encrypted in production)
    login = cleartext adminpass123

    # Permit all services by default
    default service = permit

    # Exec service configuration
    service = exec {
        priv-lvl = 15
        shell:roles = "admin"
        shell:priv-lvl = 15
    }

    # Command authorization
    cmd = .* {
        permit .*
    }
}

# User 2: tacacstest (Privilege 15 - Full Admin Access)
user = tacacstest {
    login = cleartext testpass123
    default service = permit

    service = exec {
        priv-lvl = 15
        shell:roles = "admin"
        shell:priv-lvl = 15
    }

    cmd = .* {
        permit .*
    }
}

# User 3: tacacsreadonly (Privilege 1 - Read-Only Access)
user = tacacsreadonly {
    login = cleartext readonly123
    default service = permit

    service = exec {
        priv-lvl = 1
        shell:roles = "operator"
        shell:priv-lvl = 1
    }

    # Limited command authorization for read-only
    cmd = show {
        permit .*
    }
    cmd = .* {
        deny .*
    }
}

# ==============================================================================
# GROUP CONFIGURATIONS
# ==============================================================================

group = admins {
    default service = permit
    service = exec {
        priv-lvl = 15
    }
}

group = operators {
    default service = permit
    service = exec {
        priv-lvl = 1
    }
}

# ==============================================================================
# DEFAULT SETTINGS
# ==============================================================================

# Default for all other users (deny)
user = DEFAULT {
    login = file /etc/passwd
    default service = deny
}
EOF

echo "  ✓ Configuration file created: $TACACS_CONF"

echo ""
echo "[4/6] Setting proper permissions..."
chmod 600 "$TACACS_CONF"
chown root:root "$TACACS_CONF"
echo "  ✓ Permissions set (600, root:root)"

echo ""
echo "[5/6] Creating accounting log file..."
touch /var/log/tac_plus.acct
chmod 644 /var/log/tac_plus.acct
echo "  ✓ Accounting log created: /var/log/tac_plus.acct"

echo ""
echo "[6/6] Starting/restarting TACACS+ service..."
# Try different service names (varies by distribution)
if systemctl list-unit-files | grep -q "^tacacs_plus.service"; then
    SERVICE_NAME="tacacs_plus"
elif systemctl list-unit-files | grep -q "^tac_plus.service"; then
    SERVICE_NAME="tac_plus"
fi

systemctl daemon-reload
systemctl restart $SERVICE_NAME 2>/dev/null || service $SERVICE_NAME restart
sleep 2

# Check if service is running
if systemctl is-active --quiet $SERVICE_NAME 2>/dev/null; then
    echo "  ✓ TACACS+ service is running"
else
    echo "  ⚠ WARNING: Could not verify service status"
    echo "    Try manually: sudo systemctl status $SERVICE_NAME"
fi

# Enable service to start on boot
systemctl enable $SERVICE_NAME 2>/dev/null || true
echo "  ✓ Service enabled for boot"

echo ""
echo "=========================================="
echo "✓ TACACS+ Server Setup Complete!"
echo "=========================================="
echo ""
echo "Configuration Summary:"
echo "  • Server IP: 192.168.100.175"
echo "  • Port: 49 (default)"
echo "  • Secret Key: spytest_secret123"
echo "  • Auth Type: PAP"
echo ""
echo "Configured Users:"
echo "  1. tacacsadmin   / adminpass123   (Privilege 15)"
echo "  2. tacacstest    / testpass123    (Privilege 15)"
echo "  3. tacacsreadonly / readonly123   (Privilege 1)"
echo ""
echo "Verification Commands:"
echo "  • Check service: sudo systemctl status $SERVICE_NAME"
echo "  • View logs:     sudo tail -f /var/log/syslog | grep tac_plus"
echo "  • Test port:     sudo netstat -tunlp | grep :49"
echo ""
echo "Next Steps:"
echo "  1. Verify service is listening:"
echo "     sudo netstat -tunlp | grep :49"
echo ""
echo "  2. From SONiC device, test connectivity:"
echo "     nc -zv 192.168.100.175 49"
echo ""
echo "  3. Re-run AAA authentication tests:"
echo "     ./bin/spytest --testbed testbeds/testbed_vs_1node.yaml \\"
echo "       system/AAA/test_aaa_auth.py::TestAAAAuthentication::test_auth_204_ssh_login_admin_user"
echo ""
echo "Backup of original config (if any): $TACACS_BACKUP"
echo ""
