#!/bin/bash

################################################################################
# IS-CLI Testing Automation Script
# Purpose: Run all IS-CLI Drop 1 feature tests
# Features: LLDP, Hostname, NTP, Clear ARP/ND
################################################################################

# Color codes for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m' # No Color

# Directories
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
TEST_DIR="$(dirname "$SCRIPT_DIR")"
RESULTS_DIR="$TEST_DIR/results"

# Timestamp for this test run
TIMESTAMP=$(date +"%Y%m%d_%H%M%S")
LOG_FILE="$RESULTS_DIR/test_run_${TIMESTAMP}.log"

# Test result counters
TOTAL_TESTS=0
PASSED_TESTS=0
FAILED_TESTS=0
SKIPPED_TESTS=0

################################################################################
# Functions
################################################################################

print_header() {
    echo -e "${BLUE}========================================${NC}"
    echo -e "${BLUE}$1${NC}"
    echo -e "${BLUE}========================================${NC}"
}

print_success() {
    echo -e "${GREEN}✓ $1${NC}"
}

print_error() {
    echo -e "${RED}✗ $1${NC}"
}

print_warning() {
    echo -e "${YELLOW}⚠ $1${NC}"
}

check_prerequisites() {
    print_header "Checking Prerequisites"

    # Check if pytest is installed
    if ! command -v pytest &> /dev/null; then
        print_error "pytest not found. Please install: pip3 install pytest"
        exit 1
    fi
    print_success "pytest found"

    # Check if running on SONiC system
    if [ ! -f /etc/sonic/sonic_version.yml ]; then
        print_warning "Not running on SONiC system (or sonic_version.yml not found)"
        print_warning "Some tests may fail"
    else
        print_success "SONiC system detected"
        SONIC_VERSION=$(grep "build_version:" /etc/sonic/sonic_version.yml | awk '{print $2}')
        echo "  Version: $SONIC_VERSION"
    fi

    # Check for sudo access
    if sudo -n true 2>/dev/null; then
        print_success "Sudo access available"
    else
        print_warning "Sudo access not available - some tests may fail"
    fi

    echo ""
}

run_feature_tests() {
    local feature=$1
    local test_file=$2
    local feature_name=$3

    print_header "Testing: $feature_name"

    if [ ! -f "$test_file" ]; then
        print_error "Test file not found: $test_file"
        return 1
    fi

    # Run pytest and capture results
    echo "Running pytest on $test_file..."
    pytest "$test_file" -v --tb=short --junit-xml="$RESULTS_DIR/${feature}_results_${TIMESTAMP}.xml" 2>&1 | tee -a "$LOG_FILE"

    local exit_code=${PIPESTATUS[0]}

    if [ $exit_code -eq 0 ]; then
        print_success "$feature_name tests completed successfully"
    elif [ $exit_code -eq 5 ]; then
        print_warning "$feature_name tests completed with no tests collected"
    else
        print_error "$feature_name tests failed (exit code: $exit_code)"
    fi

    echo ""
    return $exit_code
}

generate_summary() {
    print_header "Test Execution Summary"

    echo "Test Run: $TIMESTAMP"
    echo "Log File: $LOG_FILE"
    echo ""

    # Parse pytest results from log
    if [ -f "$LOG_FILE" ]; then
        echo "Detailed results in: $LOG_FILE"
        echo ""

        # Try to extract pytest summary
        if grep -q "passed" "$LOG_FILE"; then
            echo "Test Summary:"
            grep -E "(passed|failed|skipped|error)" "$LOG_FILE" | tail -5
        fi
    fi

    echo ""
}

create_results_report() {
    print_header "Creating Results Report"

    local report_file="$RESULTS_DIR/TEST_REPORT_${TIMESTAMP}.md"

    cat > "$report_file" << EOF
# IS-CLI Test Execution Report

**Date**: $(date)
**Tester**: ${USER}
**SONiC Version**: ${SONIC_VERSION:-Unknown}

## Test Execution Summary

Test run completed at: $(date)

### Test Files Executed

1. LLDP Feature Tests
2. Hostname Feature Tests
3. NTP Feature Tests
4. Clear ARP/ND Feature Tests

### Results Location

- Main Log: $LOG_FILE
- XML Results: $RESULTS_DIR/*_results_${TIMESTAMP}.xml

### Next Steps

1. Review detailed logs in: $LOG_FILE
2. Fill out complete results in: $RESULTS_DIR/TEST_RESULTS_TEMPLATE.md
3. Document any issues found
4. Create JIRA tickets for bugs
5. Update feature status in project tracker

---

Generated by: run_all_tests.sh
EOF

    print_success "Report created: $report_file"
    echo ""
}

################################################################################
# Main Execution
################################################################################

main() {
    print_header "IS-CLI Drop 1 Testing Suite"
    echo "Start Time: $(date)"
    echo "Results will be saved to: $RESULTS_DIR"
    echo ""

    # Create results directory if it doesn't exist
    mkdir -p "$RESULTS_DIR"

    # Initialize log file
    echo "IS-CLI Test Run - $TIMESTAMP" > "$LOG_FILE"
    echo "======================================" >> "$LOG_FILE"
    echo "" >> "$LOG_FILE"

    # Run prerequisite checks
    check_prerequisites

    # Run tests for each feature
    run_feature_tests "lldp" "$TEST_DIR/lldp/test_lldp_iscli.py" "LLDP (SM_ISCLI_DROP1_FEATURE5)"
    run_feature_tests "hostname" "$TEST_DIR/hostname/test_hostname_iscli.py" "Hostname (SM_ISCLI_DROP1_FEATURE6)"
    run_feature_tests "ntp" "$TEST_DIR/ntp/test_ntp_iscli.py" "NTP (SM_ISCLI_DROP1_FEATURE7)"
    run_feature_tests "clear_arp_nd" "$TEST_DIR/clear_arp_nd/test_clear_arp_nd_iscli.py" "Clear ARP/ND (SM_ISCLI_DROP1_FEATURE8)"

    # Generate summary
    generate_summary

    # Create results report
    create_results_report

    print_header "Testing Complete"
    echo "End Time: $(date)"
    echo ""
    echo "Review results in: $RESULTS_DIR"
    echo "Main log: $LOG_FILE"
}

# Run main function
main "$@"
